// <auto-generated />
using System;
using Intec.Workshop1.Customers.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intec.Workshop1.Customers.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20251216222556_UpdateFields")]
    partial class UpdateFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intec.Workshop1.Customers.Domain.ContactInformation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IsPrimary");

                    b.ToTable("ContactInformation", "customers");

                    b.HasData(
                        new
                        {
                            Id = 259446041290608640L,
                            CustomerId = 259446041282220032L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041319968769L,
                            CustomerId = 259446041319968768L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041319968770L,
                            CustomerId = 259446041319968768L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041319968772L,
                            CustomerId = 259446041319968771L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163073L,
                            CustomerId = 259446041324163072L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163074L,
                            CustomerId = 259446041324163072L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163076L,
                            CustomerId = 259446041324163075L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163077L,
                            CustomerId = 259446041324163075L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163078L,
                            CustomerId = 259446041324163075L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163080L,
                            CustomerId = 259446041324163079L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163082L,
                            CustomerId = 259446041324163081L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163083L,
                            CustomerId = 259446041324163081L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163085L,
                            CustomerId = 259446041324163084L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163086L,
                            CustomerId = 259446041324163084L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163088L,
                            CustomerId = 259446041324163087L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163089L,
                            CustomerId = 259446041324163087L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163090L,
                            CustomerId = 259446041324163087L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163092L,
                            CustomerId = 259446041324163091L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163093L,
                            CustomerId = 259446041324163091L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163095L,
                            CustomerId = 259446041324163094L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163097L,
                            CustomerId = 259446041324163096L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163098L,
                            CustomerId = 259446041324163096L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163100L,
                            CustomerId = 259446041324163099L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163101L,
                            CustomerId = 259446041324163099L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163102L,
                            CustomerId = 259446041324163099L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163104L,
                            CustomerId = 259446041324163103L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163105L,
                            CustomerId = 259446041324163103L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163107L,
                            CustomerId = 259446041324163106L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163108L,
                            CustomerId = 259446041324163106L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163109L,
                            CustomerId = 259446041324163106L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163111L,
                            CustomerId = 259446041324163110L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163112L,
                            CustomerId = 259446041324163110L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163113L,
                            CustomerId = 259446041324163110L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163115L,
                            CustomerId = 259446041324163114L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163117L,
                            CustomerId = 259446041324163116L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163118L,
                            CustomerId = 259446041324163116L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163120L,
                            CustomerId = 259446041324163119L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163122L,
                            CustomerId = 259446041324163121L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163124L,
                            CustomerId = 259446041324163123L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163125L,
                            CustomerId = 259446041324163123L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163127L,
                            CustomerId = 259446041324163126L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163128L,
                            CustomerId = 259446041324163126L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163130L,
                            CustomerId = 259446041324163129L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163131L,
                            CustomerId = 259446041324163129L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163133L,
                            CustomerId = 259446041324163132L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163135L,
                            CustomerId = 259446041324163134L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163137L,
                            CustomerId = 259446041324163136L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163138L,
                            CustomerId = 259446041324163136L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163139L,
                            CustomerId = 259446041324163136L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163141L,
                            CustomerId = 259446041324163140L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163143L,
                            CustomerId = 259446041324163142L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163144L,
                            CustomerId = 259446041324163142L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163145L,
                            CustomerId = 259446041324163142L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163147L,
                            CustomerId = 259446041324163146L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163149L,
                            CustomerId = 259446041324163148L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163150L,
                            CustomerId = 259446041324163148L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163151L,
                            CustomerId = 259446041324163148L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163153L,
                            CustomerId = 259446041324163152L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163154L,
                            CustomerId = 259446041324163152L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163155L,
                            CustomerId = 259446041324163152L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163157L,
                            CustomerId = 259446041324163156L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163159L,
                            CustomerId = 259446041324163158L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163160L,
                            CustomerId = 259446041324163158L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163161L,
                            CustomerId = 259446041324163158L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163163L,
                            CustomerId = 259446041324163162L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163165L,
                            CustomerId = 259446041324163164L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163166L,
                            CustomerId = 259446041324163164L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163167L,
                            CustomerId = 259446041324163164L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163169L,
                            CustomerId = 259446041324163168L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163170L,
                            CustomerId = 259446041324163168L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163172L,
                            CustomerId = 259446041324163171L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163174L,
                            CustomerId = 259446041324163173L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163176L,
                            CustomerId = 259446041324163175L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163177L,
                            CustomerId = 259446041324163175L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163178L,
                            CustomerId = 259446041324163175L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163180L,
                            CustomerId = 259446041324163179L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163181L,
                            CustomerId = 259446041324163179L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163182L,
                            CustomerId = 259446041324163179L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163184L,
                            CustomerId = 259446041324163183L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163185L,
                            CustomerId = 259446041324163183L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163186L,
                            CustomerId = 259446041324163183L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163188L,
                            CustomerId = 259446041324163187L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163189L,
                            CustomerId = 259446041324163187L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163191L,
                            CustomerId = 259446041324163190L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163193L,
                            CustomerId = 259446041324163192L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163194L,
                            CustomerId = 259446041324163192L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163196L,
                            CustomerId = 259446041324163195L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163198L,
                            CustomerId = 259446041324163197L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163199L,
                            CustomerId = 259446041324163197L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163200L,
                            CustomerId = 259446041324163197L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163202L,
                            CustomerId = 259446041324163201L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163204L,
                            CustomerId = 259446041324163203L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163205L,
                            CustomerId = 259446041324163203L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163206L,
                            CustomerId = 259446041324163203L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163208L,
                            CustomerId = 259446041324163207L,
                            IsPrimary = true,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163209L,
                            CustomerId = 259446041324163207L,
                            IsPrimary = false,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163211L,
                            CustomerId = 259446041324163210L,
                            IsPrimary = true,
                            IsVerified = true
                        },
                        new
                        {
                            Id = 259446041324163212L,
                            CustomerId = 259446041324163210L,
                            IsPrimary = false,
                            IsVerified = false
                        },
                        new
                        {
                            Id = 259446041324163213L,
                            CustomerId = 259446041324163210L,
                            IsPrimary = false,
                            IsVerified = true
                        });
                });

            modelBuilder.Entity("Intec.Workshop1.Customers.Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Customers", "customers");

                    b.HasData(
                        new
                        {
                            Id = 259446041282220032L,
                            Created = new DateTime(2025, 4, 17, 11, 17, 31, 625, DateTimeKind.Unspecified).AddTicks(3384),
                            CreatedBy = 52,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041319968768L,
                            Created = new DateTime(2025, 2, 3, 18, 24, 47, 144, DateTimeKind.Unspecified).AddTicks(7331),
                            CreatedBy = 59,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041319968771L,
                            Created = new DateTime(2024, 3, 27, 21, 54, 35, 243, DateTimeKind.Unspecified).AddTicks(7498),
                            CreatedBy = 34,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163072L,
                            Created = new DateTime(2024, 9, 10, 12, 42, 19, 398, DateTimeKind.Unspecified).AddTicks(5211),
                            CreatedBy = 55,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163075L,
                            Created = new DateTime(2023, 9, 28, 23, 49, 26, 751, DateTimeKind.Unspecified).AddTicks(9656),
                            CreatedBy = 85,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163079L,
                            Created = new DateTime(2024, 8, 15, 22, 54, 53, 354, DateTimeKind.Unspecified).AddTicks(9771),
                            CreatedBy = 68,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163081L,
                            Created = new DateTime(2025, 8, 14, 16, 58, 34, 489, DateTimeKind.Unspecified).AddTicks(4406),
                            CreatedBy = 62,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163084L,
                            Created = new DateTime(2025, 10, 31, 0, 13, 9, 226, DateTimeKind.Unspecified).AddTicks(6625),
                            CreatedBy = 45,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163087L,
                            Created = new DateTime(2025, 12, 3, 19, 49, 50, 795, DateTimeKind.Unspecified).AddTicks(3652),
                            CreatedBy = 40,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163091L,
                            Created = new DateTime(2025, 10, 12, 17, 22, 10, 714, DateTimeKind.Unspecified).AddTicks(5058),
                            CreatedBy = 49,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163094L,
                            Created = new DateTime(2025, 3, 8, 1, 34, 58, 311, DateTimeKind.Unspecified).AddTicks(5104),
                            CreatedBy = 84,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163096L,
                            Created = new DateTime(2025, 9, 3, 9, 25, 15, 259, DateTimeKind.Unspecified).AddTicks(1826),
                            CreatedBy = 73,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163099L,
                            Created = new DateTime(2024, 12, 15, 11, 53, 51, 640, DateTimeKind.Unspecified).AddTicks(7984),
                            CreatedBy = 22,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163103L,
                            Created = new DateTime(2024, 3, 2, 10, 47, 48, 580, DateTimeKind.Unspecified).AddTicks(3627),
                            CreatedBy = 11,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163106L,
                            Created = new DateTime(2024, 9, 19, 8, 44, 51, 330, DateTimeKind.Unspecified).AddTicks(9388),
                            CreatedBy = 50,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163110L,
                            Created = new DateTime(2023, 12, 5, 21, 59, 45, 335, DateTimeKind.Unspecified).AddTicks(1429),
                            CreatedBy = 91,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163114L,
                            Created = new DateTime(2025, 5, 9, 13, 15, 48, 795, DateTimeKind.Unspecified).AddTicks(8865),
                            CreatedBy = 85,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163116L,
                            Created = new DateTime(2024, 11, 18, 10, 49, 55, 96, DateTimeKind.Unspecified).AddTicks(1876),
                            CreatedBy = 25,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163119L,
                            Created = new DateTime(2024, 3, 20, 22, 39, 16, 750, DateTimeKind.Unspecified).AddTicks(4390),
                            CreatedBy = 61,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163121L,
                            Created = new DateTime(2023, 5, 27, 2, 45, 53, 948, DateTimeKind.Unspecified).AddTicks(724),
                            CreatedBy = 37,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163123L,
                            Created = new DateTime(2024, 5, 22, 15, 50, 40, 702, DateTimeKind.Unspecified).AddTicks(1084),
                            CreatedBy = 48,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163126L,
                            Created = new DateTime(2025, 9, 3, 17, 53, 51, 721, DateTimeKind.Unspecified).AddTicks(6258),
                            CreatedBy = 6,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163129L,
                            Created = new DateTime(2025, 3, 15, 0, 0, 19, 777, DateTimeKind.Unspecified).AddTicks(1270),
                            CreatedBy = 19,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163132L,
                            Created = new DateTime(2025, 2, 7, 13, 7, 10, 196, DateTimeKind.Unspecified).AddTicks(4659),
                            CreatedBy = 28,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163134L,
                            Created = new DateTime(2024, 9, 22, 13, 55, 14, 391, DateTimeKind.Unspecified).AddTicks(6619),
                            CreatedBy = 82,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163136L,
                            Created = new DateTime(2024, 10, 5, 4, 34, 36, 72, DateTimeKind.Unspecified).AddTicks(7843),
                            CreatedBy = 85,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163140L,
                            Created = new DateTime(2023, 2, 22, 16, 23, 27, 654, DateTimeKind.Unspecified).AddTicks(4428),
                            CreatedBy = 13,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163142L,
                            Created = new DateTime(2024, 12, 25, 5, 46, 8, 120, DateTimeKind.Unspecified).AddTicks(4096),
                            CreatedBy = 70,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163146L,
                            Created = new DateTime(2023, 2, 24, 16, 24, 23, 154, DateTimeKind.Unspecified).AddTicks(7784),
                            CreatedBy = 55,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163148L,
                            Created = new DateTime(2025, 11, 16, 22, 0, 27, 886, DateTimeKind.Unspecified).AddTicks(6368),
                            CreatedBy = 9,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163152L,
                            Created = new DateTime(2023, 4, 16, 12, 31, 50, 153, DateTimeKind.Unspecified).AddTicks(9733),
                            CreatedBy = 88,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163156L,
                            Created = new DateTime(2025, 4, 18, 8, 25, 6, 531, DateTimeKind.Unspecified).AddTicks(9251),
                            CreatedBy = 87,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163158L,
                            Created = new DateTime(2024, 10, 2, 15, 52, 58, 108, DateTimeKind.Unspecified).AddTicks(4615),
                            CreatedBy = 43,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163162L,
                            Created = new DateTime(2023, 10, 10, 15, 15, 25, 906, DateTimeKind.Unspecified).AddTicks(645),
                            CreatedBy = 70,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163164L,
                            Created = new DateTime(2025, 11, 14, 6, 26, 59, 892, DateTimeKind.Unspecified).AddTicks(3442),
                            CreatedBy = 51,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163168L,
                            Created = new DateTime(2024, 5, 8, 10, 33, 53, 826, DateTimeKind.Unspecified).AddTicks(837),
                            CreatedBy = 50,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163171L,
                            Created = new DateTime(2025, 12, 4, 4, 13, 44, 576, DateTimeKind.Unspecified).AddTicks(9665),
                            CreatedBy = 57,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163173L,
                            Created = new DateTime(2023, 4, 28, 2, 27, 22, 136, DateTimeKind.Unspecified).AddTicks(3978),
                            CreatedBy = 97,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163175L,
                            Created = new DateTime(2024, 11, 13, 1, 57, 59, 538, DateTimeKind.Unspecified).AddTicks(8232),
                            CreatedBy = 44,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163179L,
                            Created = new DateTime(2025, 4, 28, 17, 9, 21, 534, DateTimeKind.Unspecified).AddTicks(7596),
                            CreatedBy = 33,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163183L,
                            Created = new DateTime(2023, 8, 6, 18, 39, 26, 543, DateTimeKind.Unspecified).AddTicks(9829),
                            CreatedBy = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163187L,
                            Created = new DateTime(2024, 6, 22, 9, 39, 34, 60, DateTimeKind.Unspecified).AddTicks(1993),
                            CreatedBy = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163190L,
                            Created = new DateTime(2025, 11, 11, 15, 23, 55, 973, DateTimeKind.Unspecified).AddTicks(6189),
                            CreatedBy = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163192L,
                            Created = new DateTime(2024, 7, 3, 10, 47, 23, 427, DateTimeKind.Unspecified).AddTicks(5838),
                            CreatedBy = 15,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163195L,
                            Created = new DateTime(2023, 10, 2, 9, 26, 24, 601, DateTimeKind.Unspecified).AddTicks(9968),
                            CreatedBy = 15,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163197L,
                            Created = new DateTime(2024, 8, 7, 12, 2, 49, 267, DateTimeKind.Unspecified).AddTicks(987),
                            CreatedBy = 16,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163201L,
                            Created = new DateTime(2023, 11, 11, 17, 6, 44, 871, DateTimeKind.Unspecified).AddTicks(8149),
                            CreatedBy = 59,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163203L,
                            Created = new DateTime(2024, 9, 14, 17, 19, 58, 69, DateTimeKind.Unspecified).AddTicks(3411),
                            CreatedBy = 55,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163207L,
                            Created = new DateTime(2024, 6, 3, 8, 46, 48, 849, DateTimeKind.Unspecified).AddTicks(2988),
                            CreatedBy = 43,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 259446041324163210L,
                            Created = new DateTime(2024, 8, 3, 9, 11, 50, 495, DateTimeKind.Unspecified).AddTicks(3852),
                            CreatedBy = 61,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Intec.Workshop1.Customers.Domain.ContactInformation", b =>
                {
                    b.HasOne("Intec.Workshop1.Customers.Domain.Customer", null)
                        .WithMany("ContactInformations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Intec.Workshop1.Customers.Domain.ValueObjects.EMailAddress", "Email", b1 =>
                        {
                            b1.Property<long>("ContactInformationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Email");

                            b1.HasKey("ContactInformationId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("ContactInformation", "customers");

                            b1.WithOwner()
                                .HasForeignKey("ContactInformationId");
                        });

                    b.OwnsOne("Intec.Workshop1.Customers.Domain.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<long>("ContactInformationId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("PhonePrefix");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("PhoneValue");

                            b1.HasKey("ContactInformationId");

                            b1.ToTable("ContactInformation", "customers");

                            b1.WithOwner()
                                .HasForeignKey("ContactInformationId");
                        });

                    b.Navigation("Email");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("Intec.Workshop1.Customers.Domain.Customer", b =>
                {
                    b.OwnsOne("Intec.Workshop1.Customers.Domain.ValueObjects.CustomerName", "Name", b1 =>
                        {
                            b1.Property<long>("CustomerId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers", "customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Intec.Workshop1.Customers.Domain.Customer", b =>
                {
                    b.Navigation("ContactInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
